### ISSUE TITLE
Latex could not be found

### ISSUE THREAD

**Issue by rzinke** [tbenthompson/okada_wrapper#4]
I am attempting to install okada_wrapper on a Linux machine. 
$ pip install okada_wrapper nominally worked, though when I tried to run test_okada.py I got a matplotlib-related error message that says "RuntimeError: Failed to process string with tex because latex could not be found"

I have attached the full error message for reference.

Hopefully this is an easy error to solve, but I am not sure where to start. Please let me know if you can help.

Thank you, 
Rob
[Latex-error.txt](https://github.com/tbenthompson/okada_wrapper/files/5072244/Latex-error.txt)

**Comment by tbenthompson** [comment]
You can comment out line 9 here: https://github.com/tbenthompson/okada_wrapper/blob/e627882351e310466bf03fae394d17f49677571f/test_okada.py#L9

Then, the plotting functions will no longer attempt to use latex for text processing. That should solve your issue. 

Alternatively, you can install latex!
