### ISSUE TITLE
Request for help: Upgrade `okada_wrapper` to work with Python 3.12 and up. 

### ISSUE THREAD

**Issue by tbenthompson** [tbenthompson/okada_wrapper#8]
`numpy.distutils` has been deprecated and this will kill `okada_wrapper` as currently written

See the discussion and explanations here:
- https://github.com/kmaterna/Elastic_stresses_py/issues/15#
- https://numpy.org/doc/stable/reference/distutils_status_migration.html#distutils-status-migration

If someone wants to migrate `okada_wrapper` to build with scikit-build/CMake or Meson as explained in the link above, I would be happy to give you assistance. But I don't have time to lead that effort.

**Comment by dxiao** [comment]
I made a partial attempt at migrating to meson in #9, but it doesn't pass tests yet. I kinda did this on a lark and over a spare evening and that evening is now over, so if someone sees this and wants to take the last mile, I'm sure there are other folks out there that would appreciate it :)

**Comment by tobiscode** [comment]
Happy to help @tbenthompson. I use `okada_wrapper` for simple point sources in my [DISSTANS](https://github.com/tobiscode/disstans) package so there's no need for that to upgrade to TDEs. I think I have to migrate that package to meson anyway as well, and I should be able to find some spare time starting next week.

@dxiao in the meantime, could you post the error messages you got / which tests you were running?

Cheers

**Comment by dxiao** [comment]
Hey tobiscode!

You should see it in the description of the PR I linked above (#9). It's just when running the `test_okada.py` script provided in the repo.

**Comment by tobiscode** [comment]
Cross-linking my PR: https://github.com/tbenthompson/okada_wrapper/pull/11

**Comment by tobiscode** [comment]
Hi @tbenthompson, it turns out I overlooked something. While `test_okada.py` works, it does so because it ends up using a local import for `okada_wrapper`. Globally the package is installed as `DC3D`, so I have to figure out how to force the original package name. Could you please reopen the issue, and I will submit a new PR as soon as I can?

Also, in the meantime, what would you like the new version number to be? `24.03.22.1`, e.g.?

Cheers

**Comment by tbenthompson** [comment]
Ah, good catch! Thanks! Glad I hadn't done the PyPI release yet. 

I think `24.03.22` should be good. I just added you as a collaborator on the project so you should have full permissions to merge PRs, etc now.

**Comment by tobiscode** [comment]
Thanks, just saw it! Alright I'll go ahead and merge the updates. It _should_ all work now (tested both reinstalling locally and from my GitHub in an old environment with Python 3.11 as well as installing locally in a new environment with 3.12) but it would probably be good to double-check on your end before you push it to PyPI.
